quarkus:
    http:
        port: 8001
    datasource:
        db-kind: postgresql
        reactive:
            url: vertx-reactive:postgresql://localhost:5432/todoKai?user=${QUARKUS_DATASOURCE_USERNAME}&password=${QUARKUS_DATASOURCE_PASSWORD}

hibernate-orm:
    database:
        generation: drop-and-create #update
