quarkus:
    http:
        port: 8001
    datasource:
        db-kind: postgresql
        reactive:
            url: vertx-reactive:postgresql://localhost:5432/postgres?user=postgres&password=mysecretpassword

    hibernate-orm:
        database:
            generation: update
