quarkus:
    http:
        port: 8001
    datasource:
        username: ${QUARKUS_DATASOURCE_USERNAME}
        passwort: ${QUARKUS_DATASOURCE_PASSWORD}
        db-kind: postgresql
        reactive:
            url: vertx:jdbc:postgresql://localhost:5432/recipe-datenbank

hibernate-orm:
    database:
        generation: drop-and-create #update
