quarkus:
    http:
        port: 8081
    datasource:
        db-kind: postgresql
        jdbc:
            url: jdbc:postgresql://localhost:5432/recipe

hibernate-orm:
    database:
        generation: drop-and-create #update
